namespace HouseRules.Essentials.Rulesets
{
    using System.Collections.Generic;
    using DataKeys;
    using global::Types;
    using HouseRules.Core.Types;
    using HouseRules.Essentials.Rules;

    internal static class FriendlyCompetition
    {
        internal static Ruleset Create()
        {
            const string name = "Friendly Competition";
            const string description = "Get the key and be the first to the door to earn points and bragging rights! Only 25 rounds to escape...";
            const string longdesc = "<color=#FFF68F>Friendly Competition\nv1.7 by</color> <color=#FFFF00><u><b>BobtheBunny</b></u></color>\n\n<color=#000000>You only have 25 rounds to complete the game. Be the first to grab the key and get to the door! Watch out for the other heroes, they want the key too!\n\nToss bones, teleport lamps, and use your cunning wit to hinder the other heroes.\n\n--------------</color>\n\n<color=#4B0082><b>Suggested Rules:</b></color>\n<color=#000000>Call a truce until the key is found.\nBanish refreshes in 5 turns; use it on yourself at the start to scatter the heroes.\nUse Banish only on yourself.\nIf you die, will you wait for the next floor or rejoin the game?\n\n--------------\n\nMaps and bosses are determined by the Demeo Book chosen.\nAll monsters are weaker and may do unexpected things!\nEach Hero has more health and 3 rounds to be revived or crawl towards help!\nStrike Lamps to gain immunities and other effects.\nFocus Potions cause Tangled when they wear off.\nCourage is a 3x3 radius and counts as hitting another player or players and (possibly) yourself.\nStealth costs 0 Action Points.\nStats increase to a maximum of +5, and Strength and Swiftness increase +2 each time.\n\n--------------\n\n<b>Guardian:</b> Priotitizes survivability and utility.\n<b>Hunter:</b> Roots, beasts, and tricks.\n<b>Assassin:</b> Blades, alchemy, and speed.\n<b>Sorcerer:</b> Elemental spells and destruction.\n<b>Bard:</b> Songs, scrolls, tornados, and water.\n<b>Warlock:</b> Strange magics gifted from an ancient source.\n<b>Barbarian:</b> Hooks lamps, prone to anger and corruption.\n\n----------------</color>\n\n<color=#FFFFFF><u><b>What's the Point?</b></u></color>\n\n<color=#021F04><b>+1 point</color> <color=#070E38>for damaging enemies</color>\n<color=#021F04>+1 point</color> <color=#070E38>for slaying enemies</color>\n<color=#021F04>+1 point</color> <color=#070E38>for opening doors</color>\n<color=#021F04>+2 point</color> <color=#070E38>for picking up gold</color>\n<color=#021F04>+2 points</color> <color=#070E38>for damaging another player</color>\n<color=#021F04>+3 points</color> <color=#070E38>for opening chests</color>\n<color=#021F04>+4 points</color> <color=#070E38>for looting potion stands</color>\n<color=#021F04>+4 points</color> <color=#070E38>for reviving another player</color> <color=#8B0000>(they lose 4 points)</color>\n<color=#021F04>+6 points</color> <color=#070E38>for using a fountain</color>\n<color=#021F04>+8 points</color> <color=#070E38>for slaying/downing another player</color>\n<color=#021F04>+1 <u>BONUS</u> point</color> <color=#070E38>for</color> <color=#ADFF2F>anything above</color> <color=#070E38>while you have the key</color>\n\n<color=#021F04>-5 points</color> <color=#070E38>if you hurt yourself</color>\n<color=#021F04>-10 points</color> <color=#070E38>if you kill yourself</color>\n<color=#021F04>+3 points</color> <color=#070E38>if you hurt a boss</color>\n<color=#021F04>+20 points maximum</color> <color=#070E38>for unlocking the exit door <color=#8B0000>(-1 point each turn you hold the key)</color></color>\n<color=#021F04>+25 points</color> <color=#070E38>for striking the killing blow on a boss";

            var healthRule = new PieceConfigAdjustedRule(new List<PieceConfigAdjustedRule.PieceProperty>
            {
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroBarbarian, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroBarbarian, Property = "BerserkBelowHealth", Value = 0.5f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroBard, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroGuardian, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroHunter, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroRogue, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroSorcerer, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HeroWarlock, Property = "StartHealth", Value = 13 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.Verochka, Property = "StartHealth", Value = 12 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.Verochka, Property = "BerserkBelowHealth", Value = 0.35f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.Verochka, Property = "AttackDamage", Value = 4 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HealingBeacon, Property = "StartHealth", Value = 6 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.HealingBeacon, Property = "AliveForRounds", Value = 4 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.ElvenQueen, Property = "StartHealth", Value = 110 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.ElvenQueen, Property = "AttackDamage", Value = 7 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.ElvenQueen, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RatKing, Property = "StartHealth", Value = 90 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RatKing, Property = "AttackDamage", Value = 8 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RatKing, Property = "BerserkBelowHealth", Value = 0.9f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RatKing, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RatKing, Property = "MoveRange", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RootLord, Property = "StartHealth", Value = 90 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RootLord, Property = "AttackDamage", Value = 8 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RootLord, Property = "BerserkBelowHealth", Value = 0.75f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.RootLord, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.MotherCy, Property = "StartHealth", Value = 80 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.MotherCy, Property = "AttackDamage", Value = 6 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.MotherCy, Property = "BerserkBelowHealth", Value = 0.75f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.MotherCy, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.WizardBoss, Property = "StartHealth", Value = 100 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.WizardBoss, Property = "AttackDamage", Value = 7 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.WizardBoss, Property = "BerserkBelowHealth", Value = 0.9f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.WizardBoss, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.SnakeBoss, Property = "StartHealth", Value = 50 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.SnakeBoss, Property = "ActionPoint", Value = 3 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.BossTown, Property = "StartHealth", Value = 120 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.BossTown, Property = "AttackDamage", Value = 6 },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.BossTown, Property = "BerserkBelowHealth", Value = 0.75f },
                new PieceConfigAdjustedRule.PieceProperty { Piece = BoardPieceId.BossTown, Property = "MoveRange", Value = 2 },
            });

            var allowedEnergyCardsRule = new CardEnergyAdditionOverriddenRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                {
                    BoardPieceId.HeroBarbarian, new List<AbilityKey>
                    {
                        AbilityKey.GrapplingSmash,
                        AbilityKey.GrapplingSmash,
                        AbilityKey.GrapplingSmash,
                        AbilityKey.GrapplingSmash,
                        AbilityKey.GrapplingPush,
                        AbilityKey.GrapplingPush,
                        AbilityKey.GrapplingPush,
                        AbilityKey.GrapplingPush,
                        AbilityKey.GrapplingPush,
                        AbilityKey.GrapplingTotem,
                        AbilityKey.GrapplingTotem,
                        AbilityKey.GrapplingTotem,
                        AbilityKey.PlayerLeap,
                        AbilityKey.PlayerLeap,
                        AbilityKey.PlayerLeap,
                        AbilityKey.PlayerLeap,
                        AbilityKey.PlayerLeap,
                        AbilityKey.PlayerLeap,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Shockwave,
                        AbilityKey.Shockwave,
                        AbilityKey.Shockwave,
                        AbilityKey.Shockwave,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.TauntingScream,
                        AbilityKey.TauntingScream,
                        AbilityKey.TauntingScream,
                        AbilityKey.MarkOfVerga,
                        AbilityKey.MarkOfVerga,
                        AbilityKey.MarkOfVerga,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroGuardian, new List<AbilityKey>
                    {
                        AbilityKey.MiniBarricade,
                        AbilityKey.MiniBarricade,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.DropChest,
                        AbilityKey.DropChest,
                        AbilityKey.Leap,
                        AbilityKey.Leap,
                        AbilityKey.Leap,
                        AbilityKey.Regroup,
                        AbilityKey.Rejuvenation,
                        AbilityKey.RevealPath,
                        AbilityKey.Teleport,
                        AbilityKey.WarCry,
                        AbilityKey.WarCry,
                        AbilityKey.WarCry,
                        AbilityKey.WarCry,
                        AbilityKey.Whirlwind,
                        AbilityKey.Whirlwind,
                        AbilityKey.Whirlwind,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfHealing,
                        AbilityKey.BeaconOfHealing,
                        AbilityKey.BeaconOfHealing,
                        AbilityKey.BeaconOfHealing,
                        AbilityKey.BeaconOfHealing,
                        AbilityKey.PiercingSpear,
                        AbilityKey.PiercingSpear,
                        AbilityKey.PiercingSpear,
                        AbilityKey.PiercingSpear,
                        AbilityKey.EnemyJavelin,
                        AbilityKey.EnemyJavelin,
                        AbilityKey.EnemyJavelin,
                        AbilityKey.EnemyJavelin,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroBard, new List<AbilityKey>
                    {
                        AbilityKey.Tornado,
                        AbilityKey.Tornado,
                        AbilityKey.Tornado,
                        AbilityKey.Tornado,
                        AbilityKey.Tornado,
                        AbilityKey.TornadoCharge,
                        AbilityKey.TornadoCharge,
                        AbilityKey.TornadoCharge,
                        AbilityKey.TornadoCharge,
                        AbilityKey.BlockAbilities,
                        AbilityKey.BlockAbilities,
                        AbilityKey.SongOfResilience,
                        AbilityKey.SongOfResilience,
                        AbilityKey.SongOfResilience,
                        AbilityKey.SongOfResilience,
                        AbilityKey.SongOfRecovery,
                        AbilityKey.SongOfRecovery,
                        AbilityKey.ShatteringVoice,
                        AbilityKey.ShatteringVoice,
                        AbilityKey.ShatteringVoice,
                        AbilityKey.ShatteringVoice,
                        AbilityKey.WaterDive,
                        AbilityKey.WaterDive,
                        AbilityKey.WaterDive,
                        AbilityKey.WaterDive,
                        AbilityKey.WaterDive,
                        AbilityKey.ProximityMine,
                        AbilityKey.ProximityMine,
                        AbilityKey.Zap,
                        AbilityKey.Zap,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.Stealth,
                        AbilityKey.Stealth,
                        AbilityKey.Stealth,
                        AbilityKey.Blink,
                        AbilityKey.Blink,
                        AbilityKey.Blink,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroHunter, new List<AbilityKey>
                    {
                        AbilityKey.Barrage,
                        AbilityKey.Barrage,
                        AbilityKey.RatWhisperer,
                        AbilityKey.RatWhisperer,
                        AbilityKey.RatWhisperer,
                        AbilityKey.CallCompanion,
                        AbilityKey.CallCompanion,
                        AbilityKey.CallCompanion,
                        AbilityKey.CallCompanion,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.SplittingArrow,
                        AbilityKey.MarkOfAvalon,
                        AbilityKey.MarkOfAvalon,
                        AbilityKey.MarkOfAvalon,
                        AbilityKey.WebBomb,
                        AbilityKey.WebBomb,
                        AbilityKey.WebBomb,
                        AbilityKey.MonsterBait,
                        AbilityKey.MonsterBait,
                        AbilityKey.MonsterBait,
                        AbilityKey.MonsterBait,
                        AbilityKey.RootWall,
                        AbilityKey.RootWall,
                        AbilityKey.RootWall,
                        AbilityKey.RootWall,
                        AbilityKey.Whip,
                        AbilityKey.Whip,
                        AbilityKey.Whip,
                        AbilityKey.Whip,
                        AbilityKey.Whip,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroRogue, new List<AbilityKey>
                    {
                        AbilityKey.Blink,
                        AbilityKey.Bandage,
                        AbilityKey.CoinFlip,
                        AbilityKey.CoinFlip,
                        AbilityKey.CursedDagger,
                        AbilityKey.CursedDagger,
                        AbilityKey.CursedDagger,
                        AbilityKey.Flashbang,
                        AbilityKey.Flashbang,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ProximityMine,
                        AbilityKey.ProximityMine,
                        AbilityKey.ProximityMine,
                        AbilityKey.ProximityMine,
                        AbilityKey.ProximityMine,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WebBomb,
                        AbilityKey.WebBomb,
                        AbilityKey.WebBomb,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.Charge,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroSorcerer, new List<AbilityKey>
                    {
                        AbilityKey.TeleportLamp,
                        AbilityKey.TeleportLamp,
                        AbilityKey.Fireball,
                        AbilityKey.Fireball,
                        AbilityKey.Fireball,
                        AbilityKey.EnemyFireball,
                        AbilityKey.Freeze,
                        AbilityKey.Freeze,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.MagicWall,
                        AbilityKey.MagicWall,
                        AbilityKey.MagicWall,
                        AbilityKey.MagicWall,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.Teleport,
                        AbilityKey.Teleport,
                        AbilityKey.Teleport,
                        AbilityKey.Teleport,
                        AbilityKey.SummonElemental,
                        AbilityKey.SummonElemental,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.Deflect,
                        AbilityKey.Deflect,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.DeathBeam,
                        AbilityKey.DeathBeam,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
                {
                    BoardPieceId.HeroWarlock, new List<AbilityKey>
                    {
                        AbilityKey.Implode,
                        AbilityKey.Implode,
                        AbilityKey.Implode,
                        AbilityKey.Deflect,
                        AbilityKey.Deflect,
                        AbilityKey.Deflect,
                        AbilityKey.Deflect,
                        AbilityKey.Deflect,
                        AbilityKey.DeathBeam,
                        AbilityKey.DeathBeam,
                        AbilityKey.DeathBeam,
                        AbilityKey.DeathBeam,
                        AbilityKey.MinionCharge,
                        AbilityKey.MinionCharge,
                        AbilityKey.MinionCharge,
                        AbilityKey.MissileSwarm,
                        AbilityKey.MissileSwarm,
                        AbilityKey.MissileSwarm,
                        AbilityKey.Portal,
                        AbilityKey.Portal,
                        AbilityKey.Portal,
                        AbilityKey.Portal,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.Telekinesis,
                        AbilityKey.TelekineticBurst,
                        AbilityKey.TelekineticBurst,
                        AbilityKey.TelekineticBurst,
                        AbilityKey.TelekineticBurst,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.Electricity,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WeakeningShout,
                        AbilityKey.WeakeningShout,
                        AbilityKey.WeakeningShout,
                        AbilityKey.VortexDust,
                        AbilityKey.Shockwave,
                        AbilityKey.Shockwave,
                        AbilityKey.Shockwave,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.MagicWall,
                        AbilityKey.MagicWall,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.GuidingLight,
                        AbilityKey.GuidingLight,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.DrainingKiss,
                        AbilityKey.DrainingKiss,
                        AbilityKey.DrainingKiss,
                        AbilityKey.AcidSpit,
                        AbilityKey.Barrage,
                        AbilityKey.Bone,
                        AbilityKey.Deflect,
                        AbilityKey.DiseasedBite,
                        AbilityKey.DrainingKiss,
                        AbilityKey.EarthShatter,
                        AbilityKey.Electricity,
                        AbilityKey.EnemyFireball,
                        AbilityKey.EnemyFrostball,
                        AbilityKey.Fireball,
                        AbilityKey.Freeze,
                        AbilityKey.Grab,
                        AbilityKey.GodsFury,
                        AbilityKey.ImplosionExplosionRain,
                        AbilityKey.LuckPotion,
                        AbilityKey.Petrify,
                        AbilityKey.Portal,
                        AbilityKey.RatKingRatBomb,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.ScrollTsunami,
                        AbilityKey.Shockwave,
                        AbilityKey.SnakeBossShortRange,
                        AbilityKey.Telekinesis,
                        AbilityKey.VortexDust,
                        AbilityKey.VortexDust,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterDive,
                        AbilityKey.WebBomb,
                        AbilityKey.WoodBone,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.WaterLamp,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.DamageResistPotion,
                    }
                },
            });

            var allowedChestCardsRule = new CardChestAdditionOverriddenRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                {
                    BoardPieceId.HeroBarbarian, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroGuardian, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroBard, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroHunter, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroRogue, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroSorcerer, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
                {
                    BoardPieceId.HeroWarlock, new List<AbilityKey>
                    {
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.Bone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.WoodBone,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.SodiumHydroxide,
                        AbilityKey.Weaken,
                        AbilityKey.ScarePowder,
                        AbilityKey.ScarePowder,
                        AbilityKey.VortexDust,
                        AbilityKey.Regroup,
                        AbilityKey.Teleport,
                        AbilityKey.Heal,
                        AbilityKey.Heal,
                        AbilityKey.Rejuvenation,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.EyeOfAvalon,
                        AbilityKey.RevealPath,
                        AbilityKey.MiniBarricade,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.VigorPotion,
                        AbilityKey.VialOfIceImmunity,
                        AbilityKey.VialOfFireImmunity,
                        AbilityKey.Antidote,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.WaterBottle,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.GodsFury,
                        AbilityKey.Tsunami,
                        AbilityKey.SwordOfAvalon,
                        AbilityKey.BeaconOfSmite,
                        AbilityKey.MonsterBait,
                        AbilityKey.SpawnRandomLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.GasLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.IceLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.OilLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.VortexLamp,
                        AbilityKey.Grab,
                        AbilityKey.StrengthenCourage,
                        AbilityKey.CallCompanion,
                        AbilityKey.PoisonGasGrenade,
                        AbilityKey.ScrollElectricity,
                        AbilityKey.Whirlwind,
                        AbilityKey.Zap,
                    }
                },
            });

            var allowedPotionsRule = new PotionAdditionOverriddenRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                {
                    BoardPieceId.HeroBarbarian, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.MagicPotion,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroBard, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.MagicPotion,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroGuardian, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.MagicPotion,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroHunter, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.MagicPotion,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroRogue, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.MagicPotion,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.Strength,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroSorcerer, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.Strength,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.MagicPotion,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
                {
                    BoardPieceId.HeroWarlock, new List<AbilityKey>
                    {
                        AbilityKey.Heal,
                        AbilityKey.Strength,
                        AbilityKey.DamageResistPotion,
                        AbilityKey.ExtraActionPotion,
                        AbilityKey.MagicPotion,
                        AbilityKey.Speed,
                        AbilityKey.VigorPotion,
                    }
                },
            });

            var barbarianCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Grapple, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Electricity, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.PlayerLeap, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.SnakeBossShortRange, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.ExplodingLampPlaceholder, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
            };

            var warlockCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.ImplosionExplosionRain, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TeleportLamp, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MissileSwarm, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MinionCharge, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicMissile, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicMissile, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
            };

            var bardCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.StrengthenCourage, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.WaterDive, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.WaterBottle, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Tornado, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TornadoCharge, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TeleportLamp, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
            };

            var guardianCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.ReplenishArmor, ReplenishFrequency = 3 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Grab, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.BeaconOfHealing, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.PiercingSpear, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.WaterBottle, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TeleportLamp, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
            };

            var hunterCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.HunterArrow, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.HunterArrow, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.WebBomb, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.RootWall, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Whip, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TeleportLamp, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
            };

            var assassinCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Stealth, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.PoisonGasGrenade, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.WebBomb, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.ProximityMine, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.ExtraActionPotion, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.AcidSpit, ReplenishFrequency = 4 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
            };

            var sorcererCards = new List<StartCardsModifiedRule.CardConfig>
            {
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Zap, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Banish, ReplenishFrequency = 24 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Bone, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.VortexDust, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Telekinesis, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.TeleportLamp, ReplenishFrequency = 0 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.Overcharge, ReplenishFrequency = 1 },
                new StartCardsModifiedRule.CardConfig { Card = AbilityKey.MagicShield, ReplenishFrequency = 24 },
            };

            var startingCardsRule = new StartCardsModifiedRule(new Dictionary<BoardPieceId, List<StartCardsModifiedRule.CardConfig>>
            {
                { BoardPieceId.HeroWarlock, warlockCards },
                { BoardPieceId.HeroBard, bardCards },
                { BoardPieceId.HeroGuardian, guardianCards },
                { BoardPieceId.HeroHunter, hunterCards },
                { BoardPieceId.HeroRogue, assassinCards },
                { BoardPieceId.HeroSorcerer, sorcererCards },
                { BoardPieceId.HeroBarbarian, barbarianCards },
            });

            var pieceAbilityRule = new PieceAbilityListOverriddenRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                { BoardPieceId.Spider, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.EnemyStealGold } },
                { BoardPieceId.Rat, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.EnemyStealGold } },
                { BoardPieceId.GoblinFighter, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.EnemyStealGold } },
                { BoardPieceId.ElvenMystic, new List<AbilityKey> { AbilityKey.TeleportLamp, AbilityKey.TeleportEnemy } },
                { BoardPieceId.EarthElemental, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.EnemyKnockbackMelee, AbilityKey.EarthShatter, AbilityKey.EnemyJavelin, AbilityKey.Tsunami, AbilityKey.WaterDive } },
                { BoardPieceId.ReptileMutantWizard, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.Deflect, AbilityKey.DrainingKiss, AbilityKey.Electricity } },
                { BoardPieceId.Mimic, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.AcidSpit, AbilityKey.SpawnGoldPile, AbilityKey.Whirlwind, AbilityKey.LeapHeavy } },
                { BoardPieceId.RootMage, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.TeleportEnemy, AbilityKey.TeleportLamp } },
                { BoardPieceId.ChestGoblin, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.EnemyStealGold } },
                { BoardPieceId.SilentSentinel, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.ElvenSummonerDeflect, AbilityKey.Net } },
                { BoardPieceId.GiantSpider, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.DiseasedBite, AbilityKey.Grab, AbilityKey.PoisonGasGrenade, AbilityKey.SpawnSpiderlings, AbilityKey.SpiderWebshot } },
                { BoardPieceId.ScabRat, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.DiseasedBiteKnockback } },
                { BoardPieceId.KillerBee, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.ThornPowder } },
                { BoardPieceId.ElvenQueen, new List<AbilityKey> { AbilityKey.EnemyMelee, AbilityKey.TeleportLamp, AbilityKey.ElvenSummonerDeflect, AbilityKey.DrainingKiss, AbilityKey.Electricity, AbilityKey.AcidSpit, AbilityKey.EnemyFireball, AbilityKey.Grab, AbilityKey.LeapHeavy } },
            });

            var pieceBehaviourListRule = new PieceBehavioursListOverriddenRule(new Dictionary<BoardPieceId, List<Behaviour>>
            {
                { BoardPieceId.GiantSpider, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.HostileTowardsEntangled, Behaviour.RangedSpellCaster, Behaviour.SpawnPiece } },
                { BoardPieceId.SilentSentinel, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.RangedSpellCaster, Behaviour.ElvenSummonerBehaviour } },
                { BoardPieceId.ReptileMutantWizard, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.RangedAttackHighPrio, Behaviour.RangedSpellCaster, Behaviour.AttackAndRetreat } },
                { BoardPieceId.EarthElemental, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.FollowPlayerMeleeAttacker, Behaviour.RangedAttackHighPrio, Behaviour.EarthShatter } },
                { BoardPieceId.Mimic, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.RangedAttackHighPrio, Behaviour.FollowPlayerMeleeAttacker } },
                { BoardPieceId.RootMage, new List<Behaviour> { Behaviour.Patrol, Behaviour.FollowPlayerMeleeAttacker, Behaviour.AttackPlayer, Behaviour.CastOnTeam } },
                { BoardPieceId.KillerBee, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.RangedAttackHighPrio, Behaviour.FollowPlayerMeleeAttacker } },
                { BoardPieceId.ChestGoblin, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackAndRetreat, Behaviour.FollowPlayerMeleeAttacker } },
                { BoardPieceId.ElvenCultist, new List<Behaviour> { Behaviour.Patrol, Behaviour.AttackPlayer, Behaviour.Swarm } },
                { BoardPieceId.SandScorpion, new List<Behaviour> { Behaviour.Patrol, Behaviour.FollowPlayerMeleeAttacker, Behaviour.AttackAndRetreat } },
                { BoardPieceId.ElvenQueen, new List<Behaviour> { Behaviour.Patrol, Behaviour.ElvenSummonerBehaviour, Behaviour.RangedSpellCaster } },
            });

            var pieceImmunityRule = new PieceImmunityListAdjustedRule(new Dictionary<BoardPieceId, List<EffectStateType>>
            {
                { BoardPieceId.KillerBee, new List<EffectStateType> { EffectStateType.Venom, EffectStateType.Weaken1Turn, EffectStateType.Weaken2Turns, EffectStateType.Netted, EffectStateType.Tangled } },
            });

            var pieceUseWhenKilledRule = new PieceUseWhenKilledOverriddenRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                { BoardPieceId.Spider, new List<AbilityKey> { AbilityKey.EnemyDropStolenGoods } },
                { BoardPieceId.Rat, new List<AbilityKey> { AbilityKey.EnemyDropStolenGoods } },
                { BoardPieceId.GoblinFighter, new List<AbilityKey> { AbilityKey.EnemyDropStolenGoods } },
                { BoardPieceId.ChestGoblin, new List<AbilityKey> { AbilityKey.EnemyDropStolenGoods, AbilityKey.DropChest } },
                { BoardPieceId.EarthElemental, new List<AbilityKey> { AbilityKey.DeathDropWaterBottle } },
                { BoardPieceId.RootMage, new List<AbilityKey> { AbilityKey.DeathDropWaterBottle } },
                { BoardPieceId.ElvenMystic, new List<AbilityKey> { AbilityKey.DeathDropVortexDust } },
                { BoardPieceId.ElvenPriest, new List<AbilityKey> { AbilityKey.DeathDropVortexDust } },
                { BoardPieceId.BigBoiMutant, new List<AbilityKey> { AbilityKey.SpawnCorruptionNode, AbilityKey.DeathDropJeweledScarab } },
                { BoardPieceId.Brookmare, new List<AbilityKey> { AbilityKey.DeathDropWaterBottle, AbilityKey.DeathDropJeweledScarab } },
                { BoardPieceId.Cavetroll, new List<AbilityKey> { AbilityKey.DeathDropJeweledScarab } },
                { BoardPieceId.SilentSentinel, new List<AbilityKey> { AbilityKey.DeathDropJeweledScarab } },
                { BoardPieceId.GiantSlime, new List<AbilityKey> { AbilityKey.SpawnSlime, AbilityKey.AcidSpit } },
                { BoardPieceId.GiantSpider, new List<AbilityKey> { AbilityKey.SpawnSpiderlings, AbilityKey.PoisonGas } },
                { BoardPieceId.SpiderEgg, new List<AbilityKey> { AbilityKey.SpiderWebshot, AbilityKey.SpawnSpiderlings } },
            });

            var abilityActionCostRule = new AbilityActionCostAdjustedRule(new Dictionary<AbilityKey, bool>
            {
                { AbilityKey.SpawnGoldPile, false },
                { AbilityKey.TornadoCharge, false },
                { AbilityKey.Stealth, false },
                { AbilityKey.Grab, false },
                { AbilityKey.Telekinesis, false },
            });

            var aoeAdjustedRule = new AbilityAoeAdjustedRule(new Dictionary<AbilityKey, int>
            {
                { AbilityKey.StrengthenCourage, 1 },
            });

            var enemyCooldownRule = new EnemyCooldownOverriddenRule(new Dictionary<AbilityKey, int>
            {
                { AbilityKey.SpawnSummoningRiftLesser, 3 },
            });

            var abilityDamageRule = new AbilityDamageOverriddenRule(new Dictionary<AbilityKey, List<int>>
            {
                { AbilityKey.Zap, new List<int> { 2, 5 } },
                { AbilityKey.Overcharge, new List<int> { 4, 7 } },
                { AbilityKey.Petrify, new List<int> { 0, 4 } },
                { AbilityKey.EnemyJavelin, new List<int> { 2, 4 } },
                { AbilityKey.Banish, new List<int> { 0, 0 } },
                { AbilityKey.AcidSpit, new List<int> { 3, 4 } },
                { AbilityKey.PiercingSpear, new List<int> { 3, 7 } },
            });

            var pieceExtraStatsRule = new PieceExtraStatsAdjustedRule(new Dictionary<BoardPieceId, int>
            {
                { BoardPieceId.HeroGuardian, 5 },
                { BoardPieceId.HeroHunter, 5 },
                { BoardPieceId.HeroBard, 5 },
                { BoardPieceId.HeroBarbarian, 5 },
                { BoardPieceId.HeroRogue, 5 },
                { BoardPieceId.HeroWarlock, 5 },
                { BoardPieceId.HeroSorcerer, 5 },
            });

            var freeHealOnCritRule = new FreeHealOnCritRule(new List<BoardPieceId>
            {
                { BoardPieceId.HeroRogue },
                { BoardPieceId.HeroWarlock },
                { BoardPieceId.HeroBard },
                { BoardPieceId.HeroHunter },
                { BoardPieceId.HeroGuardian },
                { BoardPieceId.HeroBarbarian },
                { BoardPieceId.HeroSorcerer },
            });

            var backstabConfigRule = new BackstabConfigOverriddenRule(new List<BoardPieceId>
            {
                { BoardPieceId.HeroBard },
                { BoardPieceId.HeroRogue },
            });

            var statusEffectRule = new StatusEffectConfigRule(new List<StatusEffectData>
            {
                new StatusEffectData
                {
                    effectStateType = EffectStateType.ExtraAction,
                    durationTurns = 3,
                    damagePerTurn = 0,
                    clearOnNewLevel = false,
                    applyAfterDissipate = EffectStateType.Tangled,
                    tickWhen = StatusEffectsConfig.TickWhen.EndTurn,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Berserk,
                    durationTurns = 4,
                    damagePerTurn = 0,
                    clearOnNewLevel = false,
                    tickWhen = StatusEffectsConfig.TickWhen.EndTurn,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Courageous,
                    durationTurns = 2,
                    damagePerTurn = 0,
                    clearOnNewLevel = false,
                    tickWhen = StatusEffectsConfig.TickWhen.StartTurn,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Fearless,
                    durationTurns = 2,
                    damagePerTurn = 0,
                    clearOnNewLevel = false,
                    tickWhen = StatusEffectsConfig.TickWhen.StartTurn,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Netted,
                    durationTurns = 1,
                    damagePerTurn = 0,
                    clearOnNewLevel = false,
                    tickWhen = StatusEffectsConfig.TickWhen.EndTurn,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Antidote,
                    durationTurns = 3,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.IceImmunity,
                    durationTurns = 3,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.FireImmunity,
                    durationTurns = 3,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Invisibility,
                    durationTurns = 2,
                },
                new StatusEffectData
                {
                    effectStateType = EffectStateType.Invulnerable3,
                    durationTurns = 2,
                },
            });

            var statModifiersRule = new StatModifiersOverriddenRule(new Dictionary<AbilityKey, int>
            {
                { AbilityKey.Strength, 2 },
                { AbilityKey.Speed, 2 },
                { AbilityKey.MagicPotion, 1 },
            });

            var applyEffectOnHitRule = new ApplyEffectOnHitAdjustedRule(new Dictionary<BoardPieceId, EffectStateType>
            {
                { BoardPieceId.HealingBeacon, EffectStateType.Recovery },
                { BoardPieceId.MonsterBait, EffectStateType.Disoriented },
                { BoardPieceId.Barricade, EffectStateType.Thorns },
                { BoardPieceId.EyeOfAvalon, EffectStateType.Revealed },
                { BoardPieceId.GrapplingTotem, EffectStateType.StunSelf },
                { BoardPieceId.GasLamp, EffectStateType.Antidote },
                { BoardPieceId.IceLamp, EffectStateType.IceImmunity },
                { BoardPieceId.OilLamp, EffectStateType.FireImmunity },
                { BoardPieceId.VortexLamp, EffectStateType.Invisibility },
                { BoardPieceId.WaterLamp, EffectStateType.Recovery },
            });

            var smallLevelSequenceRule = new SmallLevelSequenceOverriddenRule(new List<string>
            {
                "ElvenFloor17",
                "SewersFloor08",
                "SewersFloor11",
                "ForestFloor02",
                "ForestFloor01",
                "ElvenFloor14",
            });

            var levelPropertiesRule = new LevelPropertiesModifiedRule(new Dictionary<string, int>
            {
                { "BigGoldPileChance", 50 },
                { "FloorOneHealingFountains", 1 },
                { "FloorOnePotionStand", 1 },
                { "FloorOneMerchant", 1 },
                { "FloorOneLootChests", 5 },
                { "FloorOneGoldMaxAmount", 300 },
                { "FloorOneSellswords", 1 },
                { "FloorOneVillagers", 1 },
                { "FloorTwoHealingFountains", 1 },
                { "FloorTwoPotionStand", 2 },
                { "FloorTwoMerchant", 1 },
                { "FloorTwoVillagers", 2 },
                { "FloorTwoLootChests", 7 },
                { "FloorTwoGoldMaxAmount", 700 },
                { "FloorTwoSellswords", 1 },
                { "FloorTwoBeggars", 1 },
                { "FloorThreeHealingFountains", 1 },
                { "FloorThreePotionStand", 1 },
                { "FloorThreeLootChests", 2 },
                { "FloorThreeMerchant", 1 },
            });

            var pieceReplenishRule = new PieceReplenishAbilityEveryLevelRule(new Dictionary<BoardPieceId, List<AbilityKey>>
            {
                { BoardPieceId.HeroHunter, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroSorcerer, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroBard, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroBarbarian, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroWarlock, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroGuardian, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
                { BoardPieceId.HeroRogue, new List<AbilityKey> { AbilityKey.Banish, AbilityKey.MagicShield } },
            });

            var pointGainRule = new PointGainRule(new PointGainRule.Points
            { KillEnemy = 1, KillPlayer = 8, KillSelf = -10, KillBoss = 25, HurtEnemy = 1, HurtPlayer = 2, HurtSelf = -5,  HurtBoss = 3, Keyholder = 1, UnlockDoor = 20, LootGold = 2, LootChest = 3, LootStand = 4, OpenDoor = 1, UseFountain = 6, RevivePlayer = 4 });

            var roundLimitRule = new RoundCountLimitedRule(25);
            var enemyRespawnDisabledRule = new EnemyRespawnDisabledRule(true);
            var cardEnergyFromAttackRule = new CardEnergyFromAttackMultipliedRule(1.5f);
            var cardEnergyFromRecyclingRule = new CardEnergyFromRecyclingMultipliedRule(1.0f);
            var enemyHealthScaledRule = new EnemyHealthScaledRule(0.5f);
            var enemyAttackScaledRule = new EnemyAttackScaledRule(0.35f);
            var pieceKeyholderRule = new PieceKeyholderRule(true);
            var orderRandomizedRule = new TurnOrderRandomizedRule(true);

            return Ruleset.NewInstance(
                name,
                description,
                longdesc,
                pieceReplenishRule,
                orderRandomizedRule,
                pieceKeyholderRule,
                allowedChestCardsRule,
                allowedEnergyCardsRule,
                allowedPotionsRule,
                aoeAdjustedRule,
                abilityDamageRule,
                abilityActionCostRule,
                applyEffectOnHitRule,
                enemyAttackScaledRule,
                enemyHealthScaledRule,
                enemyCooldownRule,
                enemyRespawnDisabledRule,
                freeHealOnCritRule,
                cardEnergyFromAttackRule,
                cardEnergyFromRecyclingRule,
                smallLevelSequenceRule,
                statusEffectRule,
                statModifiersRule,
                backstabConfigRule,
                pieceAbilityRule,
                pieceBehaviourListRule,
                pieceExtraStatsRule,
                pieceImmunityRule,
                pieceUseWhenKilledRule,
                pointGainRule,
                healthRule,
                startingCardsRule,
                roundLimitRule,
                levelPropertiesRule);
        }
    }
}
